### ISSUE TITLE
Deployment problems summary

### ISSUE THREAD

**Issue by liuhaocg** [IBM/cloudland#20]
1.Is it necessary to run allinone.sh in cland user?
2.Selinux should be disabled
3.If the IP of hypervisor is 192.168.1.0/24, some unknown problems maybe happen in deploy process, eg: cloudland compile failed, clui compile failed etc. Haven't tried 172.16.20.0/24, same question may happen too?
4.After I changed IP of hypervisor from 192.168.1.0/24 to 192.168.168.0/24, most problems solved, but cloudland did not compile, need to compile it manually.Before compile, need to stop cloudlet.
5.The env param ADMIN_PASSWD I changed in allinone.sh, but it did not set as the default password of admin, is it ok?
6.cloudland project is too big, nearly 80M, is it ok? When git clone in bad network environment, may cause clone fail problem.
7.Suggest to transfer some code to Aliyun or some repo in China.

**Comment by Catherine2019** [comment]
Thanks for your summary, will give you update when I'm solving it one by one

**Comment by Catherine2019** [comment]
1. This is for security and safety consideration for processes are running with non-root user.
2. Selinux now needs to be set with permissive, working on enforcing now.

**Comment by Catherine2019** [comment]
For 3, now the default IP range for br5000 is changed to 192.168.71.1 so the chance of duplication should be rare.
For 4, I think this should be because grpc was not deployed at the first place, so the compile didn't go through.
For 5, this bug is resolved.
For 6, reduced a few files, not sure how much it can help yet, will do more later.
For 7, the large files have been moved to aliyun.
