### ISSUE TITLE
[Bug] 'hyper' field is always in editable mode

### ISSUE THREAD

**Issue by suridaddy** [IBM/cloudland#66]
No way to know if the migration occur or not?

**Comment by Catherine2019** [comment]
As it takes time to finish a VM migration, in this time duration, this operation shouldn't be able to submitted again.
It is not enough to simply set a flag in database, because the status will be synchronized from backend. We need to make sure report_rc.sh is reporting the right migration status by touching a status file

**Comment by xieqiang2020** [comment]
Fixed by #76
